# Generated by Django 2.0.7 on 2018-07-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150, verbose_name='Product Name')),
                ('product_price', models.FloatField(verbose_name='Price')),
                ('product_category', models.CharField(max_length=150, verbose_name='Category')),
                ('product_brand', models.CharField(max_length=150, verbose_name='Brand')),
            ],
        ),
    ]
